import './assets/styles/globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { config } from '@fortawesome/fontawesome-svg-core';
import Header from '@/components/Header/header';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { NextAuthProvider } from './providers';

config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Plan Together',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fr">
      <body className="bg-gray-100  overflow-hidden">
        <NextAuthProvider>
          <Header />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
