import './assets/styles/globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { jakartaSans } from '@/app/utilities/typography';

export const metadata: Metadata = {
  title: 'Plan Together',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fr">
      <body
        className={`bg-gray-100  dark:bg-gray-800 ${jakartaSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
